sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ilyanesterow/container_deploy -f Dockerfile.dev .

script:
  - docker run -e CI=true ilyanesterow/container_deploy npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-284065031581"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET