sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ilyanesterow/container_deploy -f Dockerfile.dev .

script:
  - docker run -e CI=true ilyanesterow/container_deploy npm run test